sudo: false

language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - coverage run test.py

after_success:
  - codecov
  - coverage report -m

deploy:
  skip_cleanup: true
  provider: pypi
  user: "irgang"
  password:
    secure: "mPYhrmzvEHmC41QRqjHGarvjOOlA4nTcEcz+l3Wn6D02arTJOidOVTRVquEn21+z02k2FU3rMO0ASOKuQk6ThEPBLQTKHp596/IEeEXmFRjrsw4IMHukTssYwoBu92ss9l7T4YLoztVL9kUAS3i70quv7frAmJMyMvU/odpjdKt+2gpXbp3TjdlPJ/uPzSVOl8cdCBGF4KFk/tEkBquWDRJp8pJx+V7uBeRLeq6VSTKhRxAq+9nRt89MG0im
nTP/AAujx2VguoVrkHcB3m92OxkHRdOOjjMZz2FoqjCQNRI8V//U98KKniirfnYdaUc8zk/ohv/JjUPAw4DwUUDOMpCzCVmdxDavjtvQIh7CCXRj9sbTtL12mkP5yae0qKbBXz/rOCnCNODlpKLKl199fDHOkjJrnOn+PDbO+nkRXa4LD/dCaXpu55vQnrC/PmY1GOQWT4OiFa6gCal+RDy9Dlykwtz3tE+R3+61bQfB7pzRtYsovFS40t4lnLU9SfbDS
yLMng+mE8bKvhAgotuPt2MSKV6NNbmJXmHrZig+YO8N70B8C+frwM/Wozvk7Pz3nydeUBL8v0wBzynsvco6kVs0g6NhszgRi7d16cOZ8G3vN6bZVa4xxkWIzSPbKy3hMg8Z94pxTrVl/o5QY67hIf7mCvlOJ5o6xo8q0UDlSdg="
  on:
    branch: master
    tags: true
  distributions: "sdist"
